// horusec-manager/src/pages/External/Auth/Horusec/Login/index.tsx
/**
 * Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState, FormEvent } from 'react';
import Styled from './styled';
import { isValidEmail, isEmptyString } from 'helpers/validators';
import { useHistory, useRouteMatch } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Field } from 'helpers/interfaces/Field';
import useAuth from 'helpers/hooks/useAuth';

function LoginScreen() {
  const { t } = useTranslation();
  const history = useHistory();
  const { path } = useRouteMatch();
  const { login, loginInProgress } = useAuth();

  const [email, setEmail] = useState<Field>({ value: '', isValid: false });
  const [password, setPassword] = useState<Field>({
    value: '',
    isValid: false,
  });

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (email.isValid && password.isValid) {
      login(email.value, password.value).then(() => {
        history.push('/organization');
      });
    }
  };

  return (
    <Styled.Form onSubmit={handleSubmit}>
      <Styled.Field
        label={t('LOGIN_SCREEN.EMAIL')}
        name="email"
        type="text"
        onChangeValue={(field: Field) => setEmail(field)}
        invalidMessage={t('LOGIN_SCREEN.INVALID_EMAIL')}
        validation={isValidEmail}
      />

      <Styled.Field
        label={t('LOGIN_SCREEN.PASSWORD')}
        name="password"
        type="password"
        onChangeValue={(field: Field) => setPassword(field)}
        validation={isEmptyString}
        invalidMessage={t('LOGIN_SCREEN.INVALID_PASS')}
      />

      <Styled.ForgotPass
        onClick={() => history.push(`${path}/recovery-password`)}
      >
        {t('LOGIN_SCREEN.FORGOT_PASS')}
      </Styled.ForgotPass>

      <Styled.Submit
        isDisabled={!password.isValid || !email.isValid}
        isLoading={loginInProgress}
        text={t('LOGIN_SCREEN.SUBMIT')}
        type="submit"
        rounded
      />

      <Styled.Register
        onClick={() => history.push(`${path}/create-account`)}
        outline
        text={t('LOGIN_SCREEN.NO_ACCOUNT')}
        rounded
      />
    </Styled.Form>
  );
}

export default LoginScreen;

// horusec-manager/src/views/public/auth/login/index.vue
<!--
 Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <v-card
    elevation="10"
    :loading="isLoading"
    :disabled="isLoading"
  >
    <v-form
      v-model="form.valid"
      @submit.prevent
    >
      <HorusecLogo />

      <v-container>
        <v-row>
          <v-col cols="12">
            <v-text-field
              v-model="form.email.value"
              :rules="form.email.rules"
              :label="$i18n.t('login.form.email_field')"
              required
              light
              @keypress.enter="form.valid ? submit() : null"
            />
          </v-col>
        </v-row>

        <v-row>
          <v-col cols="12">
            <v-text-field
              v-model="form.password.value"
              :rules="form.password.rules"
              :label="$i18n.t('login.form.password_field')"
              required
              light
              type="password"
              @keypress.enter="form.valid ? submit() : null"
            />

            <router-link
              class="recovery-pass"
              :to="{ name: 'recovery-password' }"
            >
              {{ $i18n.t('login.forgot_password') }}
            </router-link>
          </v-col>
        </v-row>
      </v-container>

      <v-btn
        color="primary"
        large
        :disabled="!form.valid"
        @click="submit()"
      >
        {{ $i18n.t('login.form.btn_login') }}
      </v-btn>

      <v-btn
        color="primary lighten"
        large
        @click="goToSignUp()"
      >
        {{ $i18n.t('login.form.btn_sign_up') }}
      </v-btn>
    </v-form>
  </v-card>
</template>

<script src="./script.js" />

<style lang="scss">
  @import './style.scss';
</style>
