// horusec-manager-new/src/pages/Internal/Home/Dashboard/index.tsx
/**
 * Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState } from 'react';
import Styled from './styled';
import Filters from './Filters';
import { FilterValues } from 'helpers/interfaces/FilterValues';

import TotalDevelopers from './TotalDevelopers';
import TotalRepositories from './TotalRepositories';
import AllVulnerabilities from './AllVulnerabilities';
import VulnerabilitiesByDeveloper from './VulnerabilitiesByDeveloper';
import VulnerabilitiesByLanguage from './VulnerabilitiesByLanguage';
import VulnerabilitiesByRepository from './VulnerabilitiesByRepository';
import VulnerabilitiesTimeLine from './VulnerabilitiesTimeLine';
import VulnerabilitiesDetails from './VulnerabilitiesDetails';

interface Props {
  type: 'company' | 'repository';
}

const Dashboard: React.FC<Props> = ({ type }) => {
  const [filters, setFilters] = useState<FilterValues>(null);

  return (
    <Styled.Wrapper>
      <Filters type={type} onApply={(values) => setFilters(values)} />

      <Styled.Row>
        <TotalDevelopers filters={filters} />

        {type === 'company' ? <TotalRepositories filters={filters} /> : null}

        <AllVulnerabilities filters={filters} />
      </Styled.Row>

      <Styled.Row>
        <VulnerabilitiesByDeveloper filters={filters} />

        {type === 'company' ? (
          <VulnerabilitiesByRepository filters={filters} />
        ) : null}
      </Styled.Row>

      <Styled.Row>
        <VulnerabilitiesByLanguage filters={filters} />

        <VulnerabilitiesTimeLine filters={filters} />
      </Styled.Row>

      <Styled.Row>
        <VulnerabilitiesDetails filters={filters} />
      </Styled.Row>
    </Styled.Wrapper>
  );
};

export default Dashboard;

// horusec-manager/src/views/private/internal-pages/dashboard/index.vue
<!--
 Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <section class="dashboard">
    <v-tabs
      v-model="indexTabSelected"
      dark
      background-color="blue darken-4 primary"
      show-arrows
      @change="setTabSelected($event, true)"
    >
      <v-tabs-slider color="blue darken-4 primary" />

      <v-tab
        v-for="(tab, i) in getAllTabs"
        :key="i"
      >
        {{ tab.label }}
      </v-tab>
    </v-tabs>

    <v-tabs-items
      v-if="indexTabSelected != null && !isLoading"
      v-model="indexTabSelected"
      style="height: calc(100% - 48px);"
    >
      <v-tab-item
        v-for="(tab, i) in getAllTabs"
        :key="i"
      >
        <v-card flat>
          <v-main class="dashboard-content">
            <StartDateEndDatePicker
              :has-action="true"
              :disabled="disabledSearch"
            />

            <CompanyCharts
              v-if="getAllTabs[indexTabSelected].type === 'company'"
              @set-disabled-search="($event) => disabledSearch = $event"
            />

            <RepositoryCharts
              v-if="getAllTabs[indexTabSelected].type === 'repository'"
              @set-disabled-search="($event) => disabledSearch = $event"
            />
          </v-main>
        </v-card>
      </v-tab-item>
    </v-tabs-items>
  </section>
</template>

<style lang="scss">
  @import './style.scss';
</style>

<script src="./script.js" />
