// horusec-manager/src/pages/External/Auth/index.tsx
/**
 * Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import { getCurrentConfig } from 'helpers/localStorage/horusecConfig';
import { ObjectLiteral } from 'helpers/interfaces/ObjectLiteral';
import { Splash } from 'components';

import HorusecAuth from './Horusec';
import KeycloakAuth from './Keycloak';
import LDAPAuth from './LDAP';
import useAuth from 'helpers/hooks/useAuth';

const Auth = () => {
  const { fetchConfigInProgress } = useAuth();
  const { authType } = getCurrentConfig();

  const getAuthenticator = (auth: string) => {
    const authenticators: ObjectLiteral = {
      horusec: HorusecAuth,
      ldap: LDAPAuth,
      keycloak: KeycloakAuth,
    };

    return authenticators[auth];
  };

  const renderAuthenticator = () => {
    if (authType) {
      const Authenticator = getAuthenticator(authType);
      return <Authenticator />;
    }
  };

  return (
    <>
      <Splash isVisible={fetchConfigInProgress} />

      {renderAuthenticator()}
    </>
  );
};

export default Auth;

// horusec-manager/src/views/public/auth/index.vue
<!--
 Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<template>
  <div class="container-auth gradient-container">
    <router-view />

    <Footer />
  </div>
</template>

<script src="./script.js"></script>

<style lang="scss">
  @import './style.scss';
</style>
